added request_timeout to ollama, default set to 30.0 in settings.yaml…
zylon-ai/private-gpt pull request #1735
Opened 2024-03-15 04:57 UTC by sgresham

… and settings-ollama.yaml

2024-03-15 08:36 UTC, imartinez reviewed
Love it, thanks! Added a comment, let me know what you think

2024-03-15 08:36 UTC, imartinez commented on settings-ollama.yaml
> +  request_timeout: 30.0 # Time elapsed until ollama times out the request. Default is 30s. Format is float.
Could you default it to 60 or even 90? People running on CPU are having trouble with 30.

2024-03-15 08:38 UTC, imartinez requested changes
Aren't you missing the addition of the setting to `settings.py`? 
I'd add it with a default value there. Otherwise passing a None value may break the integration.

2024-03-15 21:33 UTC, sgresham commented
I have added settings now to settings.py. Apologies for missing it.

2024-03-19 20:28 UTC, imartinez approved these changes

2024-03-20 20:35 UTC, imartinez commented
Merged in https://github.com/zylon-ai/private-gpt/pull/1773

2024-03-20 20:35 UTC, closed without merging