Model Temperature editing enabled on UI
zylon-ai/private-gpt pull request #1878
Opened 2024-04-23 08:28 UTC by Castolus

Model Temperature editing enabled on UI. This option enables the user to "play" with the model´s spontaneity without having to restart the code every time. 
Visualization enabled from "settings.yaml". Range of Temperature goes from 0.05 to 0.95 since 0 and 1 are not possible values for this parameter. 
I didn´t add the rest of parameters (top_k, top_p, etc..)  as i belive it´d bee too much info in the UI. But I´m open to do it if you consider it´d be nice.

2024-04-30 12:42 UTC, imartinez requested changes
Good addition. Please check my comments to avoid breaking a prev functionality.

2024-04-30 12:42 UTC, imartinez commented on private_gpt/settings/settings.py
> -    access_token: str = Field(
Please don't remove this

2024-07-08 09:52 UTC, jaluma requested changes

2024-07-08 09:52 UTC, jaluma commented on private_gpt/ui/ui.py
> +        self._model_temperature = model_temperature_input
Where do you use `self.model_temperature`? You are setting the property, but not sending it to the server. Are there any changes missing? @Castolus

2024-07-08 09:52 UTC, jaluma commented on private_gpt/ui/ui.py
> +
I would suggest adding a button to be clearer. Right now, we have to press Enter to accept the change. It doesn't seem to me the most accessible function.

2024-07-18 05:02 UTC, closed without merging