Adding MistralAI mode
zylon-ai/private-gpt pull request #2065
Opened 2024-08-22 15:19 UTC by itsliamdowd

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I added a Mistral mode where users can interact with Mistral's API for chat completion and generating embeddings. This mode requires the llama-index-embeddings-mistralai package in llama index to work properly and uses the already installed llama-index-llms-openai-like package for the llm to work.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

2024-08-28 06:30 UTC, jaluma requested changes
Thank you for your contribution, it is very helpful. Please review the comments below :)

2024-08-28 06:30 UTC, jaluma commented on private_gpt/components/embedding/embedding_component.py
> +            case "mistral":
Please switch to `mistralai` or another literal. This may cause confusion

2024-08-28 06:30 UTC, jaluma commented on private_gpt/components/llm/llm_component.py
> +                )
This is unnecessary since you are using OpenAILike. Are there any specific `mistralai` implementation?

2024-08-28 06:30 UTC, jaluma commented on private_gpt/settings/settings.py
> +    model: str
also rename it

2024-08-28 06:30 UTC, jaluma commented on private_gpt/ui/ui.py
> +                            "mistral": config_settings.gemini.model,
you are selecting `gemini.model` :)

2024-08-28 15:34 UTC, itsliamdowd commented
Thanks for the corrections - I removed the Mistral LLM case but this results in settings being pulled from the OpenAI settings page instead of the Mistral settings page. Should I eliminate the Mistral settings page altogether?

2024-08-28 15:47 UTC, jaluma commented
> Thanks for the corrections - I removed the Mistral LLM case but this results in settings being pulled from the OpenAI settings page instead of the Mistral settings page. Should I eliminate the Mistral settings page altogether?

I would say yes. With `settings-mistralai.yaml`, it's all that you need to load load the model, right? Reviewing again the PR, I realised that the documentation update would be missing :)

2024-08-28 17:36 UTC, itsliamdowd commented
Yes it would need `api_base`, `api_key`, `model`, `embedding_model`, `prompt_style`, and `request_timeout`. I removed the `settings-mistral.yaml` because all of these can be included in the OpenAI like settings with a documentation update.

2024-09-09 06:55 UTC, jaluma submitted a review, later dismissed
Sorry for delay @itsliamdowd.
LGTM. Thank you.
Can you merge `main` and execute `poetry lock --no-update`?

2024-09-23 09:26 UTC, pabloogc approved these changes

2024-09-24 06:31 UTC, merged