Fix docker-compose.yaml
zylon-ai/private-gpt pull request #2073
Opened 2024-08-30 13:54 UTC by gabryz95

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of Change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x ] I can run the project via docker-compose now.

This change solves the problem described in issue #2071

2024-08-31 19:12 UTC, gkesik approved these changes

2024-08-31 19:13 UTC, gkesik approved these changes

2024-09-09 07:02 UTC, jaluma requested changes
Please revert the changes I have marked for you. On the other hand, to solve this problem, what we have to do is to retry the initial connection to ollama. E.g. https://stackoverflow.com/questions/50246304/using-python-decorators-to-retry-request

2024-09-09 07:02 UTC, jaluma commented on docker-compose.yaml
> +  ollama:
Please go back to `ollama-cpu`. Traeffik will route each request to these children service

2024-09-16 15:04 UTC, jaluma commented
We close this PR since the changes are not valid. They don't fix anything, they just prevent them from happening. Fixed at: https://github.com/zylon-ai/private-gpt/pull/2059

2024-09-16 15:04 UTC, closed without merging