Add default mode option to settings
zylon-ai/private-gpt pull request #2078
Opened 2024-09-10 02:31 UTC by basicbloke

# Description

Add default mode to settings files

## Type of Change

- [*] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [*] I stared at the code and made sure it makes sense
- [*] Tested functionality within UI

**Test Configuration**:
Python: 3.11.9

## Checklist:

[*] I have performed a self-review of my code
[*] My changes generate no new warnings

2024-09-10 07:15 UTC, jaluma requested changes
Please check my comments. Also, can you add this to `settings.yaml`?

2024-09-10 07:15 UTC, jaluma commented on private_gpt/settings/settings.py
> +    )
It's better idea configure like literal (enum)

2024-09-10 16:17 UTC, basicbloke commented
need to run tests and fix

2024-09-11 11:43 UTC, jaluma requested changes

2024-09-11 11:43 UTC, jaluma commented on settings.yaml
> +  default_mode: "Summarize"
By default, RAG please :)

2024-09-11 12:14 UTC, basicbloke commented on settings.yaml
> +  default_mode: "Summarize"
😎

2024-09-11 14:39 UTC, jaluma approved these changes
LGTM

Thank you!

2024-09-23 09:27 UTC, pabloogc approved these changes

2024-09-24 06:33 UTC, merged